projects:
  Team05-appsync-api:
    schemaPath: src/graphql/schema.json
    includes:
      - cdk-backend/graphql/shema.graphql
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: codegens
        docsFilePath: cdk-backend/graphql
        region: us-east-1
        apiId: zadpj2bvcfclvoaoa7ivfrzffm
        maxDepth: 2
